version: '3'
services:
    server:
        image: erikaulin/unitycacheserver:latest
        container_name: unitycacheserver
        ports:
          - "8126:8126"
        volumes:
            - cachevolume:/opt/cache
volumes:
    cachevolume: